#  Visual
ID_THICKNESS = 2

ID_SCALE = 1.0

ID_COLOR = (255, 0, 0)

RECTANGLE_COLOR = (0, 255, 0)

#  Algorithm parameters
MAX_TIME_TO_BE_TENTATIVE = 3

MAHALANOBIS_DISTANCE_THRESHOLD = 120

MAX_TIME_WITHOUT_USE_FOR_TRACKER = 20

MAX_TIME_WITHOUT_USE_FOR_TENTATIVE_TRACKER = 10

LAST_CHANCE_IOU_THRESHOLD = 0.1
